/**
 * Domain types for key management abstraction
 */

export enum KeyType {
  STELLAR_ED25519 = 'STELLAR_ED25519',
  ETHEREUM_SECP256K1 = 'ETHEREUM_SECP256K1',
}

export enum KeyStatus {
  ACTIVE = 'ACTIVE',
  ROTATED = 'ROTATED',
  COMPROMISED = 'COMPROMISED',
  ARCHIVED = 'ARCHIVED',
}

/**
 * Keypair generated by the key management service
 */
export interface GeneratedKeyPair {
  publicKey: string;
  privateKeyMaterial: string; // For immediate encryption, never stored
  keyType: KeyType;
  metadata?: Record<string, any>;
}

/**
 * Encrypted key material for storage
 */
export interface EncryptedKeyMaterial {
  encryptedData: string;
  encryptionVersion: number;
  keyType: KeyType;
  publicKey: string;
}

/**
 * Signature result from signing operation
 */
export interface SignatureResult {
  signature: string;
  publicKey: string;
  algorithm: string;
  timestamp: Date;
}

/**
 * Audit log for key operations
 */
export interface KeyOperationAudit {
  operation: 'GENERATE' | 'SIGN' | 'ROTATE' | 'REVOKE' | 'ACCESS';
  keyId: string;
  publicKey: string;
  timestamp: Date;
  metadata?: Record<string, any>;
  success: boolean;
  errorMessage?: string;
}
